name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            node-version: '14'
          - os: macos-13
            node-version: '14'
          - os: ubuntu-latest
            node-version: '14'

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configure Electron mirrors
        run: |
          npm config set electron_mirror "https://npmmirror.com/mirrors/electron/"
          echo "ELECTRON_BUILDER_BINARIES_MIRROR=https://npmmirror.com/mirrors/electron/" >> $GITHUB_ENV
          echo "ELECTRON_MIRROR=https://npmmirror.com/mirrors/electron/" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Build and publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build -- --publish always
